/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javase.ex2;

import java.util.Random;

/**
 *
 * @author Michel
 */
public class Exemplo2_1 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo2
     */
    public Exemplo2_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBOcultarMostrar = new javax.swing.JButton();
        JBMover = new javax.swing.JButton();
        JBRedimensionar = new javax.swing.JButton();
        JBTeste = new javax.swing.JButton();
        JLTESTE = new javax.swing.JLabel();
        JTFTeste = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBOcultarMostrar.setText("Ocultar");
        JBOcultarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBOcultarMostrarActionPerformed(evt);
            }
        });

        JBMover.setText("Mover");
        JBMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBMoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBMoverMouseEntered(evt);
            }
        });
        JBMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMoverActionPerformed(evt);
            }
        });

        JBRedimensionar.setText("Redimensionar");
        JBRedimensionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRedimensionarActionPerformed(evt);
            }
        });

        JBTeste.setText("TESTE");
        JBTeste.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JBTesteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JBTesteFocusLost(evt);
            }
        });

        JLTESTE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLTESTE.setText("TESTE");

        JTFTeste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFTesteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(JBOcultarMostrar)
                        .addGap(96, 96, 96)
                        .addComponent(JBMover)
                        .addGap(108, 108, 108)
                        .addComponent(JBRedimensionar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBTeste)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLTESTE, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBOcultarMostrar)
                    .addComponent(JBMover)
                    .addComponent(JBRedimensionar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBTeste)
                    .addComponent(JLTESTE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(676, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBOcultarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBOcultarMostrarActionPerformed
        if (JBTeste.isVisible()) {
            JBTeste.setVisible(false);
            JBOcultarMostrar.setText("Mostrar");
        } else {
            JBTeste.setVisible(true);
            JBOcultarMostrar.setText("Ocultar");
        }
    }//GEN-LAST:event_JBOcultarMostrarActionPerformed

    private void JBMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMoverActionPerformed
        Random gerador = new Random();
        int x = gerador.nextInt(1851);
        int y = gerador.nextInt(951);
        System.out.println("x " + x + " y " + y);
        JBTeste.setLocation(x, y);
    }//GEN-LAST:event_JBMoverActionPerformed

    private void JBRedimensionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRedimensionarActionPerformed
        Random gerador = new Random();
        int x = gerador.nextInt(1851);
        int y = gerador.nextInt(951);
        System.out.println("x " + x + " y " + y);
        JBTeste.setSize(x, y);
    }//GEN-LAST:event_JBRedimensionarActionPerformed

    private void JBTesteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JBTesteFocusGained
        JLTESTE.setText("Ganhou Foco.");
    }//GEN-LAST:event_JBTesteFocusGained

    private void JBTesteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JBTesteFocusLost
         JLTESTE.setText("Perdeu Foco.");
    }//GEN-LAST:event_JBTesteFocusLost

    private void JTFTesteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTesteKeyReleased
        JLTESTE.setText("Código "+evt.getKeyCode());
    }//GEN-LAST:event_JTFTesteKeyReleased

    private void JBMoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBMoverMouseClicked
       JLTESTE.setText("CLICOU.");
    }//GEN-LAST:event_JBMoverMouseClicked

    private void JBMoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBMoverMouseEntered
         JLTESTE.setText("O que isso faz?");
    }//GEN-LAST:event_JBMoverMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo2_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBMover;
    private javax.swing.JButton JBOcultarMostrar;
    private javax.swing.JButton JBRedimensionar;
    private javax.swing.JButton JBTeste;
    private javax.swing.JLabel JLTESTE;
    private javax.swing.JTextField JTFTeste;
    // End of variables declaration//GEN-END:variables
}
