/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javase.ex8;

import javase.ex5.*;
import java.awt.Color;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Michel
 */
public class Exemplo8_6 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo5
     */
    public Exemplo8_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        JSBVermelho = new javax.swing.JScrollBar();
        JSBVerde = new javax.swing.JScrollBar();
        JSBAzul = new javax.swing.JScrollBar();
        JPCorFinal = new javax.swing.JPanel();
        JLVermelho = new javax.swing.JLabel();
        JLVerde = new javax.swing.JLabel();
        JLAzul = new javax.swing.JLabel();
        JSliderRed = new javax.swing.JSlider();
        JSliderGreen = new javax.swing.JSlider();
        JSliderBlue = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JSBVermelho.setBlockIncrement(1);
        JSBVermelho.setMaximum(256);
        JSBVermelho.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        JSBVermelho.setVisibleAmount(1);
        JSBVermelho.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                valorCorVermelha(evt);
            }
        });

        JSBVerde.setBlockIncrement(1);
        JSBVerde.setMaximum(256);
        JSBVerde.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        JSBVerde.setVisibleAmount(1);
        JSBVerde.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                valorCorVerde(evt);
            }
        });

        JSBAzul.setBlockIncrement(1);
        JSBAzul.setMaximum(256);
        JSBAzul.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        JSBAzul.setVisibleAmount(1);
        JSBAzul.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                valorCorAzul(evt);
            }
        });

        JPCorFinal.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout JPCorFinalLayout = new javax.swing.GroupLayout(JPCorFinal);
        JPCorFinal.setLayout(JPCorFinalLayout);
        JPCorFinalLayout.setHorizontalGroup(
            JPCorFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        JPCorFinalLayout.setVerticalGroup(
            JPCorFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        JLVermelho.setText("Vermelho: 0");

        JLVerde.setText("Verde: 0");

        JLAzul.setText("Azul: 0");

        JSliderRed.setMaximum(255);
        JSliderRed.setValue(0);
        JSliderRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizanteVermelho(evt);
            }
        });

        JSliderGreen.setMaximum(255);
        JSliderGreen.setValue(0);
        JSliderGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizanteVerde(evt);
            }
        });

        JSliderBlue.setMaximum(255);
        JSliderBlue.setValue(0);
        JSliderBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DeslizanteAzul(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(JSBVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JLVermelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(JSBAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JLAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(JSBVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JLVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(JPCorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JSliderRed, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSliderBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSliderGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSBVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLVermelho))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSBVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLVerde))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JSBAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JSliderRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JSliderGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JSliderBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPCorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLAzul)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorCorVermelha(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_valorCorVermelha
        JLVermelho.setText("Vermelho: " + evt.getValue());
        JPCorFinal.setBackground(new Color(evt.getValue(), 0, 0));
    }//GEN-LAST:event_valorCorVermelha

    private void valorCorVerde(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_valorCorVerde
        JLVerde.setText("Verde: " + evt.getValue());
        JPCorFinal.setBackground(new Color(0, evt.getValue(), 0));
    }//GEN-LAST:event_valorCorVerde

    private void valorCorAzul(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_valorCorAzul
        JLAzul.setText("Azul: " + evt.getValue());
        JPCorFinal.setBackground(new Color(0, 0, evt.getValue()));
    }//GEN-LAST:event_valorCorAzul

    private void deslizanteVermelho(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizanteVermelho
        deslizante();
    }//GEN-LAST:event_deslizanteVermelho

    private void deslizanteVerde(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizanteVerde
        deslizante();
    }//GEN-LAST:event_deslizanteVerde

    private void DeslizanteAzul(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DeslizanteAzul
        deslizante();
    }//GEN-LAST:event_DeslizanteAzul

    public void deslizante() {
        JLVermelho.setText("Vermelho: " + JSliderRed.getValue());
        JLVerde.setText("Verde: " + JSliderGreen.getValue());
        JLAzul.setText("Azul: " + JSliderBlue.getValue());
        JPCorFinal.setBackground(new Color(JSliderRed.getValue(),
                JSliderGreen.getValue(), JSliderBlue.getValue()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo8_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLAzul;
    private javax.swing.JLabel JLVerde;
    private javax.swing.JLabel JLVermelho;
    private javax.swing.JPanel JPCorFinal;
    private javax.swing.JScrollBar JSBAzul;
    private javax.swing.JScrollBar JSBVerde;
    private javax.swing.JScrollBar JSBVermelho;
    private javax.swing.JSlider JSliderBlue;
    private javax.swing.JSlider JSliderGreen;
    private javax.swing.JSlider JSliderRed;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
